const DOMAIN = "http://localhost/capacitaciones/",
  API = `${DOMAIN}api/v1.0/`,
  LOGIN = `${API}login/`,
  ADMINS = `${DOMAIN}administrador/`,
  STUDENTS = `${DOMAIN}estudiante/`,
  EMPRESAS = `${API}empresas/`,
  DEPTOS = `${API}departamentos/`,
  USERS = `${API}usuarios/`,
  CURSOS = `${API}cursos/`,
  TEMAS = `${API}temas/`,
  ROLES = `${API}roles/`,
  KEY_SESSION = "GPO20231001";

export default {
  ADMINS,
  API,
  DOMAIN,
  STUDENTS,
  KEY_SESSION,
  LOGIN,
  EMPRESAS,
  DEPTOS,
  USERS,
  CURSOS,
  TEMAS,
  ROLES,
};
